In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
import sys
sys.version

'3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]'

# Creating Arrays #

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [10]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
np.arange(3.0)

array([0., 1., 2.])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(20,10)

array([], dtype=int32)

In [19]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [20]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [21]:
np.arange(-20,-10)


array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [34]:
np.arange(30,20)

array([], dtype=int32)

In [35]:
ar = np.arange(-30,20)
ar


array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [36]:
np.arange(10,10)

array([], dtype=int32)

In [37]:
np.arange()

TypeError: arange() requires stop to be specified.

In [38]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [39]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [40]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [41]:
np.zeros(3)

array([0., 0., 0.])

In [42]:
np.zeros(5, dtype =int)

array([0, 0, 0, 0, 0])

In [45]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [48]:
zeros = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [49]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [51]:
zero = np.zeros([2,2])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [52]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [53]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [54]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [56]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [59]:
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [60]:
n

(6, 7)

In [61]:
n1

(6, 8)

In [62]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [63]:
np.ones(3)

array([1., 1., 1.])

In [64]:
np.ones(4)

array([1., 1., 1., 1.])

In [65]:
n

(6, 7)

In [66]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [67]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [68]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [69]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [70]:
np.ones(2)

array([1., 1.])

In [71]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
np.ones((6,10), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [74]:
range(5)

range(0, 5)

In [75]:
r = range(5)
r

range(0, 5)

In [76]:
for i in r:
    print(i)

0
1
2
3
4


In [77]:
list(range(5))

[0, 1, 2, 3, 4]

In [78]:
range(1,10)

range(1, 10)

In [79]:
list(range(1,19,3))

[1, 4, 7, 10, 13, 16]

In [80]:
list(range(1,10,3))

[1, 4, 7]

In [81]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [82]:
rand(3,2)

NameError: name 'rand' is not defined

In [83]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [84]:
np.random.rand(5)

array([0.75865546, 0.03483078, 0.55006614, 0.99194142, 0.53667871])

In [86]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [87]:
np.random.rand(2,4)

array([[0.68112283, 0.2264407 , 0.05889297, 0.70167367],
       [0.15795055, 0.35478146, 0.8031372 , 0.73317721]])

In [89]:
np.random.randint(2,4)

2

In [90]:
np.random.randint(0.1)

ValueError: high <= 0

In [91]:
np.random.randint(2,20)

17

In [92]:
np.random.randint(0,1) 

0

In [93]:
np.random.randint(10,20,5)

array([12, 16, 10, 17, 11])

In [94]:
np.random.randint(1,6,4)

array([2, 3, 5, 1])

In [95]:
np.random.rand(3)

array([0.27088048, 0.40280862, 0.74644071])

In [96]:
np.random.randint(1)

0

In [97]:
np.random.randint(30,20,10)

ValueError: low >= high

In [98]:
np.random.randint(-30,20,10)

array([ -4,  -8, -11,   1,  -3,  -7,  18, -25,   2,  18])

In [99]:
np.random.randint(20,30,10)

array([20, 21, 27, 23, 21, 27, 27, 28, 21, 25])

In [100]:
np.random.randint(5,9)

6

In [101]:
np.random.randint(10,21,3)

array([19, 12, 16])

In [102]:
np.random.randint(1,12,10)

array([11,  7,  2,  6, 11,  2,  8, 11,  8,  7])

In [103]:
np.random.randint(10,40,(10,10))

array([[33, 15, 32, 26, 13, 26, 36, 19, 27, 14],
       [22, 25, 25, 33, 30, 35, 18, 18, 37, 16],
       [32, 14, 37, 22, 38, 18, 21, 12, 18, 30],
       [23, 39, 33, 19, 16, 36, 23, 23, 28, 27],
       [27, 33, 39, 14, 28, 25, 35, 36, 20, 12],
       [32, 16, 12, 17, 21, 14, 30, 36, 15, 33],
       [39, 27, 15, 12, 13, 25, 23, 21, 14, 17],
       [39, 14, 32, 24, 35, 14, 29, 21, 37, 27],
       [28, 37, 14, 23, 17, 38, 34, 13, 39, 26],
       [27, 12, 13, 36, 10, 39, 15, 10, 16, 25]])

In [104]:
np.random.randint(1,100,(12,12))

array([[ 9, 29, 99, 85,  4, 95, 38, 10, 37, 79, 82, 57],
       [89, 51, 41, 80, 98, 72, 78, 87, 48, 16, 54, 50],
       [12, 46, 98, 42, 11, 61, 94, 28, 53, 56,  4, 18],
       [72,  9, 85, 26, 47, 24,  1, 24, 30, 97, 44, 57],
       [ 8, 67, 71, 91, 73, 64, 54, 11, 26, 11, 13, 50],
       [30, 35, 90, 44, 85, 85, 15, 21, 90, 83, 72,  1],
       [47, 97, 17, 21, 49, 49, 38,  2, 21, 95, 24, 19],
       [10,  7, 14, 16, 80, 30, 19, 37, 35, 27, 46, 98],
       [49, 51, 70, 11, 37,  3, 13, 54, 60, 68, 98, 95],
       [95, 59, 87, 36, 18,  3, 67, 91, 26, 94, 33, 48],
       [76, 53, 71, 57, 20, 95, 53, 48, 56, 31, 48, 67],
       [14, 29, 70, 85, 45, 70, 47, 77, 68, 72, 67, 51]])

In [105]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [106]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [108]:
b = np.random.randint(10,20,(5,4))
b

array([[12, 13, 15, 10],
       [14, 19, 13, 12],
       [10, 18, 11, 15],
       [18, 17, 13, 15],
       [19, 10, 17, 11]])

In [109]:
type(b)

numpy.ndarray

In [110]:
b

array([[12, 13, 15, 10],
       [14, 19, 13, 12],
       [10, 18, 11, 15],
       [18, 17, 13, 15],
       [19, 10, 17, 11]])

In [111]:
b[:]

array([[12, 13, 15, 10],
       [14, 19, 13, 12],
       [10, 18, 11, 15],
       [18, 17, 13, 15],
       [19, 10, 17, 11]])

In [112]:
b[1:3]

array([[14, 19, 13, 12],
       [10, 18, 11, 15]])

In [114]:
b

array([[12, 13, 15, 10],
       [14, 19, 13, 12],
       [10, 18, 11, 15],
       [18, 17, 13, 15],
       [19, 10, 17, 11]])

In [115]:
b[1,2]

13

In [116]:
b

array([[12, 13, 15, 10],
       [14, 19, 13, 12],
       [10, 18, 11, 15],
       [18, 17, 13, 15],
       [19, 10, 17, 11]])

In [117]:
b[1,3]

12

In [122]:
b[1,-4]

14

In [119]:
b

array([[12, 13, 15, 10],
       [14, 19, 13, 12],
       [10, 18, 11, 15],
       [18, 17, 13, 15],
       [19, 10, 17, 11]])

In [123]:
b[2:3]

array([[10, 18, 11, 15]])

In [124]:
b

array([[12, 13, 15, 10],
       [14, 19, 13, 12],
       [10, 18, 11, 15],
       [18, 17, 13, 15],
       [19, 10, 17, 11]])

In [131]:
b[-5:-3]

array([[12, 13, 15, 10],
       [14, 19, 13, 12]])

In [133]:
b[0,-2]

15

In [134]:
b

array([[12, 13, 15, 10],
       [14, 19, 13, 12],
       [10, 18, 11, 15],
       [18, 17, 13, 15],
       [19, 10, 17, 11]])

In [135]:
b[-5,-3]

13

In [136]:
b

array([[12, 13, 15, 10],
       [14, 19, 13, 12],
       [10, 18, 11, 15],
       [18, 17, 13, 15],
       [19, 10, 17, 11]])

In [141]:
b[3:2]

array([], shape=(0, 4), dtype=int32)

In [142]:
b[-5,-3]

13

In [143]:
b

array([[12, 13, 15, 10],
       [14, 19, 13, 12],
       [10, 18, 11, 15],
       [18, 17, 13, 15],
       [19, 10, 17, 11]])

In [144]:
b[-4,2]

13

In [145]:
np.random.randint(10,20,(4,4))

array([[16, 17, 14, 17],
       [19, 12, 10, 18],
       [12, 17, 18, 12],
       [18, 19, 10, 10]])

In [146]:
b

array([[12, 13, 15, 10],
       [14, 19, 13, 12],
       [10, 18, 11, 15],
       [18, 17, 13, 15],
       [19, 10, 17, 11]])

In [147]:
b[-4,-2]

13

In [148]:
b

array([[12, 13, 15, 10],
       [14, 19, 13, 12],
       [10, 18, 11, 15],
       [18, 17, 13, 15],
       [19, 10, 17, 11]])

In [149]:
b[-4:2]

array([[14, 19, 13, 12]])

In [150]:
b[:]


array([[12, 13, 15, 10],
       [14, 19, 13, 12],
       [10, 18, 11, 15],
       [18, 17, 13, 15],
       [19, 10, 17, 11]])

# Operations #

In [151]:
a = np.random.randint(10,20,10)
a

array([16, 17, 19, 12, 18, 18, 14, 18, 17, 13])

In [152]:
id(a)

2285735201360

In [163]:
arr

array([0, 1, 2, 3, 4, 5])

In [164]:
arr2 = np.random.randint(0,50,(10,10))

In [165]:
arr2

array([[16, 11, 33, 10, 38, 46, 22, 29,  1,  6],
       [ 2, 28, 32, 36, 14, 38,  6,  5, 15, 21],
       [12, 49, 23, 29, 13, 45, 18, 39,  2, 44],
       [49, 30, 10, 13,  2,  2,  4, 17, 39, 24],
       [35, 40,  2, 14, 21, 13,  3, 11, 23,  2],
       [ 3, 13, 35, 24, 38, 39, 34, 12,  9,  4],
       [ 1,  2, 41,  5, 33, 15, 22, 19, 14, 13],
       [19, 10, 49, 15, 45, 40, 46, 19, 37, 15],
       [25, 36, 15, 42, 11, 24, 29, 25, 46, 22],
       [ 2, 35, 13, 18, 41, 13, 33, 48, 40, 15]])

In [166]:
arr

array([0, 1, 2, 3, 4, 5])

In [167]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [168]:
arr2[:]

array([[16, 11, 33, 10, 38, 46, 22, 29,  1,  6],
       [ 2, 28, 32, 36, 14, 38,  6,  5, 15, 21],
       [12, 49, 23, 29, 13, 45, 18, 39,  2, 44],
       [49, 30, 10, 13,  2,  2,  4, 17, 39, 24],
       [35, 40,  2, 14, 21, 13,  3, 11, 23,  2],
       [ 3, 13, 35, 24, 38, 39, 34, 12,  9,  4],
       [ 1,  2, 41,  5, 33, 15, 22, 19, 14, 13],
       [19, 10, 49, 15, 45, 40, 46, 19, 37, 15],
       [25, 36, 15, 42, 11, 24, 29, 25, 46, 22],
       [ 2, 35, 13, 18, 41, 13, 33, 48, 40, 15]])

In [159]:
arr

array([0, 1, 2, 3, 4, 5])

In [160]:
arr[:4]

array([0, 1, 2, 3])

In [161]:
arr2[:]

array([[29, 18, 37, 19, 45, 32,  7, 43, 39, 40],
       [45, 35, 22, 27, 19, 30,  3, 30, 20, 37],
       [35, 33, 36, 43, 14, 37,  2, 19, 42, 19],
       [ 2, 20, 42, 36, 11, 20, 45,  3, 24, 23],
       [22,  0, 10, 17, 48,  4, 37, 42, 38, 10],
       [21, 18, 46, 12,  6, 26,  8, 10, 26,  4],
       [ 7, 17, 15, 22, 11,  1,  8, 24, 22,  2],
       [ 5, 23,  8, 29, 35, 46, 19, 16, 16,  1],
       [49, 33,  2,  4, 22, 25, 15, 31,  9, 25],
       [ 2, 21, 29, 14, 42,  7, 11, 21, 26, 20]])

In [162]:
arr2

array([[29, 18, 37, 19, 45, 32,  7, 43, 39, 40],
       [45, 35, 22, 27, 19, 30,  3, 30, 20, 37],
       [35, 33, 36, 43, 14, 37,  2, 19, 42, 19],
       [ 2, 20, 42, 36, 11, 20, 45,  3, 24, 23],
       [22,  0, 10, 17, 48,  4, 37, 42, 38, 10],
       [21, 18, 46, 12,  6, 26,  8, 10, 26,  4],
       [ 7, 17, 15, 22, 11,  1,  8, 24, 22,  2],
       [ 5, 23,  8, 29, 35, 46, 19, 16, 16,  1],
       [49, 33,  2,  4, 22, 25, 15, 31,  9, 25],
       [ 2, 21, 29, 14, 42,  7, 11, 21, 26, 20]])

In [173]:
arr2[1,4]

14

In [174]:
arr2

array([[16, 11, 33, 10, 38, 46, 22, 29,  1,  6],
       [ 2, 28, 32, 36, 14, 38,  6,  5, 15, 21],
       [12, 49, 23, 29, 13, 45, 18, 39,  2, 44],
       [49, 30, 10, 13,  2,  2,  4, 17, 39, 24],
       [35, 40,  2, 14, 21, 13,  3, 11, 23,  2],
       [ 3, 13, 35, 24, 38, 39, 34, 12,  9,  4],
       [ 1,  2, 41,  5, 33, 15, 22, 19, 14, 13],
       [19, 10, 49, 15, 45, 40, 46, 19, 37, 15],
       [25, 36, 15, 42, 11, 24, 29, 25, 46, 22],
       [ 2, 35, 13, 18, 41, 13, 33, 48, 40, 15]])

In [175]:
arr2

array([[16, 11, 33, 10, 38, 46, 22, 29,  1,  6],
       [ 2, 28, 32, 36, 14, 38,  6,  5, 15, 21],
       [12, 49, 23, 29, 13, 45, 18, 39,  2, 44],
       [49, 30, 10, 13,  2,  2,  4, 17, 39, 24],
       [35, 40,  2, 14, 21, 13,  3, 11, 23,  2],
       [ 3, 13, 35, 24, 38, 39, 34, 12,  9,  4],
       [ 1,  2, 41,  5, 33, 15, 22, 19, 14, 13],
       [19, 10, 49, 15, 45, 40, 46, 19, 37, 15],
       [25, 36, 15, 42, 11, 24, 29, 25, 46, 22],
       [ 2, 35, 13, 18, 41, 13, 33, 48, 40, 15]])

In [176]:
arr2[1,4]

14

In [177]:
arr2

array([[16, 11, 33, 10, 38, 46, 22, 29,  1,  6],
       [ 2, 28, 32, 36, 14, 38,  6,  5, 15, 21],
       [12, 49, 23, 29, 13, 45, 18, 39,  2, 44],
       [49, 30, 10, 13,  2,  2,  4, 17, 39, 24],
       [35, 40,  2, 14, 21, 13,  3, 11, 23,  2],
       [ 3, 13, 35, 24, 38, 39, 34, 12,  9,  4],
       [ 1,  2, 41,  5, 33, 15, 22, 19, 14, 13],
       [19, 10, 49, 15, 45, 40, 46, 19, 37, 15],
       [25, 36, 15, 42, 11, 24, 29, 25, 46, 22],
       [ 2, 35, 13, 18, 41, 13, 33, 48, 40, 15]])

In [178]:
arr2[-5,5]

39

In [179]:
arr2

array([[16, 11, 33, 10, 38, 46, 22, 29,  1,  6],
       [ 2, 28, 32, 36, 14, 38,  6,  5, 15, 21],
       [12, 49, 23, 29, 13, 45, 18, 39,  2, 44],
       [49, 30, 10, 13,  2,  2,  4, 17, 39, 24],
       [35, 40,  2, 14, 21, 13,  3, 11, 23,  2],
       [ 3, 13, 35, 24, 38, 39, 34, 12,  9,  4],
       [ 1,  2, 41,  5, 33, 15, 22, 19, 14, 13],
       [19, 10, 49, 15, 45, 40, 46, 19, 37, 15],
       [25, 36, 15, 42, 11, 24, 29, 25, 46, 22],
       [ 2, 35, 13, 18, 41, 13, 33, 48, 40, 15]])

In [180]:
arr2[-1,-2]

40

In [181]:
arr2[::-1]

array([[ 2, 35, 13, 18, 41, 13, 33, 48, 40, 15],
       [25, 36, 15, 42, 11, 24, 29, 25, 46, 22],
       [19, 10, 49, 15, 45, 40, 46, 19, 37, 15],
       [ 1,  2, 41,  5, 33, 15, 22, 19, 14, 13],
       [ 3, 13, 35, 24, 38, 39, 34, 12,  9,  4],
       [35, 40,  2, 14, 21, 13,  3, 11, 23,  2],
       [49, 30, 10, 13,  2,  2,  4, 17, 39, 24],
       [12, 49, 23, 29, 13, 45, 18, 39,  2, 44],
       [ 2, 28, 32, 36, 14, 38,  6,  5, 15, 21],
       [16, 11, 33, 10, 38, 46, 22, 29,  1,  6]])

In [182]:
arr2

array([[16, 11, 33, 10, 38, 46, 22, 29,  1,  6],
       [ 2, 28, 32, 36, 14, 38,  6,  5, 15, 21],
       [12, 49, 23, 29, 13, 45, 18, 39,  2, 44],
       [49, 30, 10, 13,  2,  2,  4, 17, 39, 24],
       [35, 40,  2, 14, 21, 13,  3, 11, 23,  2],
       [ 3, 13, 35, 24, 38, 39, 34, 12,  9,  4],
       [ 1,  2, 41,  5, 33, 15, 22, 19, 14, 13],
       [19, 10, 49, 15, 45, 40, 46, 19, 37, 15],
       [25, 36, 15, 42, 11, 24, 29, 25, 46, 22],
       [ 2, 35, 13, 18, 41, 13, 33, 48, 40, 15]])

In [183]:
arr2[::-3]

array([[ 2, 35, 13, 18, 41, 13, 33, 48, 40, 15],
       [ 1,  2, 41,  5, 33, 15, 22, 19, 14, 13],
       [49, 30, 10, 13,  2,  2,  4, 17, 39, 24],
       [16, 11, 33, 10, 38, 46, 22, 29,  1,  6]])

In [184]:
arr2

array([[16, 11, 33, 10, 38, 46, 22, 29,  1,  6],
       [ 2, 28, 32, 36, 14, 38,  6,  5, 15, 21],
       [12, 49, 23, 29, 13, 45, 18, 39,  2, 44],
       [49, 30, 10, 13,  2,  2,  4, 17, 39, 24],
       [35, 40,  2, 14, 21, 13,  3, 11, 23,  2],
       [ 3, 13, 35, 24, 38, 39, 34, 12,  9,  4],
       [ 1,  2, 41,  5, 33, 15, 22, 19, 14, 13],
       [19, 10, 49, 15, 45, 40, 46, 19, 37, 15],
       [25, 36, 15, 42, 11, 24, 29, 25, 46, 22],
       [ 2, 35, 13, 18, 41, 13, 33, 48, 40, 15]])

In [185]:
arr2[:-3]

array([[16, 11, 33, 10, 38, 46, 22, 29,  1,  6],
       [ 2, 28, 32, 36, 14, 38,  6,  5, 15, 21],
       [12, 49, 23, 29, 13, 45, 18, 39,  2, 44],
       [49, 30, 10, 13,  2,  2,  4, 17, 39, 24],
       [35, 40,  2, 14, 21, 13,  3, 11, 23,  2],
       [ 3, 13, 35, 24, 38, 39, 34, 12,  9,  4],
       [ 1,  2, 41,  5, 33, 15, 22, 19, 14, 13]])

In [186]:
arr

array([0, 1, 2, 3, 4, 5])

In [187]:
arr.max()

5

In [188]:
arr.min()

0

In [189]:
arr

array([0, 1, 2, 3, 4, 5])

In [190]:
arr.mean()

2.5

In [191]:
arr

array([0, 1, 2, 3, 4, 5])

In [192]:
arr.median

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [194]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

In [195]:
arr

array([0, 1, 2, 3, 4, 5])

In [196]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [197]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [198]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [199]:
arr

array([0, 1, 2, 3, 4, 5])

In [201]:
arr.reshape(2,4) 

ValueError: cannot reshape array of size 6 into shape (2,4)

In [202]:
arr

array([0, 1, 2, 3, 4, 5])

In [203]:
arr.reshape(2,3,order='c')

array([[0, 1, 2],
       [3, 4, 5]])

In [204]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [205]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [206]:
arr

array([0, 1, 2, 3, 4, 5])

In [207]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [209]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

In [210]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [211]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [213]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [214]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [215]:
arr

array([0, 1, 2, 3, 4, 5])

In [216]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# Indexing #

In [218]:
mat = np.arange(0,100).reshape(10,10)

In [219]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [220]:
row = 4
col = 5

In [221]:
col

5

In [222]:
row

4

In [223]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
mat[row,col]

45

In [225]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [226]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [227]:
col = 6

In [228]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [229]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [230]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [231]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [232]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [233]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [234]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [235]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [236]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [237]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [238]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [239]:
row

4

In [240]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [241]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [242]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [243]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [244]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [245]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [246]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [247]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [248]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [249]:
row

4

In [250]:
col

6

In [251]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [252]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [253]:
mat[1,4]

14

In [254]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [255]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [256]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [257]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [258]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [259]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [260]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [261]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [262]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [263]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [264]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [265]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [266]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [267]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [268]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [269]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [270]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [271]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [272]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [273]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [274]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [275]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [276]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [277]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [278]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [279]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [280]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [281]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [282]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [283]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [284]:
mat[0,1]

1

In [285]:
mat[1,6]

16

In [286]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [287]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [288]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [289]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [290]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [291]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [292]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [294]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [295]:
mat[3,5]

35

In [296]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [297]:
mat[1:2,2:4]

array([[12, 13]])

In [298]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [299]:
mat[2:3,2:3]

array([[22]])

In [300]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [301]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [302]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [303]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [304]:
mat[2:3,4:5]

array([[24]])

# Masking #

In [305]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [306]:
id(mat)

2285734479696

In [307]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [308]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [309]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [310]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [311]:
mat[mat==50]

array([50])

In [312]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [313]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [314]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [315]:
a1 = mat[mat<50]

In [316]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [317]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [318]:
a2 = mat[mat>50]

In [319]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [320]:
a3 = mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [321]:
a4 = mat[mat==50]
a4

array([50])

# python program to generat otp #

In [325]:
import random
def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp
otp_length = 4
otp = generate_otp(otp_length)
print(f"your OTP is:{otp}")

your OTP is:2102


In [327]:
def wish():
    print('good even')
wish()
def wish():
    print('good even')
wish()
def wish():
    print('good even')
wish()


good even
good even
good even


In [328]:
def wish():
    print('good even')
wish()
wish()
wish()



good even
good even
good even


In [329]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x000002143075AC40>


In [330]:
x = [1,2,3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
